version: '3.9'

services:
  bot:
    container_name: bot-app
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
#    environment:
#      POSTGRES_HOST: 46.19.64.203
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - bot-network

networks:
  bot-network:
