version: '3.9'

services:
  bot:
    container_name: bot-app
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - bot-network

networks:
  bot-network:
