name: Deploy app

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start working
        run: echo Start working!
      - name: Get files from repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  prepare:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Stop current containers
        run: docker-compose down
      - name: Remove unused containers
        run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Get files from repo
        uses: actions/checkout@v3
      - name: Pull to docker
        run: docker-compose up -d --build

